version: '3.4'

services:
  kafka-manager:
    image: kafkamanager/kafka-manager:3.0.0.4
    ports:
      - "9087:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "iwannaknow"
    depends_on:
      - "zookeeper"
      - "kafka0"
      - "kafka1"
      - "kafka2"
    networks:
      - kafka-net

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
    deploy:
      placement:
        constraints: [node.hostname == $NODE0_HOST_NAME]
    networks:
      - kafka-net
    volumes:
      - zk-data0:/var/lib/zookeeper/data
      - zk-txn-logs0:/var/lib/zookeeper/log

  kafka0:
    image: confluentinc/cp-kafka:5.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka0:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
    depends_on:
      - "zookeeper"
    deploy:
      placement:
        constraints: [node.hostname == $NODE0_HOST_NAME]
    networks:
      - kafka-net
    volumes:
      - kafka-data0:/var/lib/kafka/data

  kafka1:
    image: confluentinc/cp-kafka:5.5.0
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka1:19093,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
    depends_on:
      - "zookeeper"
    deploy:
      placement:
        constraints: [node.hostname == $NODE1_HOST_NAME]
    networks:
      - kafka-net
    volumes:
      - kafka-data1:/var/lib/kafka/data

  kafka2:
    image: confluentinc/cp-kafka:5.5.0
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka2:19094,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9094"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
    depends_on:
      - "zookeeper"
    deploy:
      placement:
        constraints: [node.hostname == $NODE2_HOST_NAME]
    networks:
      - kafka-net
    volumes:
      - kafka-data2:/var/lib/kafka/data

  rest-proxy:
    image: confluentinc/cp-kafka-rest:5.5.0
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka0:19092,PLAINTEXT://kafka1:19093,PLAINTEXT://kafka2:19094"
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082/"
      KAFKA_REST_HOST_NAME: "rest-proxy"
    depends_on:
      - "kafka0"
      - "kafka1"
      - "kafka2"
    networks:
      - kafka-net

  topics-ui:
    image: landoop/kafka-topics-ui:0.9.4
    ports:
      - "8085:8085"
    environment:
      PORT: "8085"
      PROXY: "true"
      KAFKA_REST_PROXY_URL: "http://rest-proxy:8082"
    depends_on:
      - "rest-proxy"
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: overlay

volumes:
  zk-data0:
  zk-txn-logs0:
  kafka-data0:
  kafka-data1:
  kafka-data2:
