version: '3.4'

services:
  kafka-manager:
    image: kafkamanager/kafka-manager:3.0.0.4
    ports:
      - "9087:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "iwannaknow"
    depends_on:
      - "zookeeper"
      - "kafka0"
    networks:
      - kafka-net

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
    deploy:
      placement:
        constraints: [node.hostname == $NODE0_HOST_NAME]
    networks:
      - kafka-net

  kafka0:
    image: confluentinc/cp-kafka:5.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka0:19092,EXTERNAL://${DOCKER_HOST0_IP}:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
    depends_on:
      - "zookeeper"
    deploy:
      placement:
        constraints: [node.hostname == $NODE0_HOST_NAME]
    networks:
      - kafka-net

  rest-proxy:
    image: confluentinc/cp-kafka-rest:5.5.0
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka0:19092"
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082/"
      KAFKA_REST_HOST_NAME: "rest-proxy"
    depends_on:
      - "kafka0"
    networks:
      - kafka-net

  topics-ui:
    image: landoop/kafka-topics-ui:0.9.4
    ports:
      - "8085:8085"
    environment:
      PORT: "8085"
      PROXY: "true"
      KAFKA_REST_PROXY_URL: "http://rest-proxy:8082"
    depends_on:
      - "rest-proxy"
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: overlay
